# Generated by Django 2.1.5 on 2019-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_auto_20190212_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='name',
            field=models.CharField(blank=True, default='a', max_length=255),
        ),
    ]
