# Generated by Django 2.1.5 on 2019-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0003_auto_20190212_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
